# Generated by Django 5.2.6 on 2026-09-11 14:57

import django.db.models.deletion
import django.utils.timezone
import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_option', models.PositiveSmallIntegerField()),
                ('parallel_form_group', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['topic', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['lecture_number'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-semester', 'name'],
                'unique_together': {('semester', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_number', models.PositiveIntegerField()),
                ('phase', models.CharField(choices=[('PRE', 'Преди лекцията'), ('POST', 'След лекцията')], max_length=8)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('join_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('reveal_answers', models.BooleanField(default=False)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.cohort')),
            ],
            options={
                'verbose_name_plural': 'quizzes',
                'ordering': ['lecture_number', 'phase'],
            },
        ),
        migrations.CreateModel(
            name='QuizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('measurement', models.CharField(choices=[('BASELINE', 'Базова линия'), ('ACQUISITION', 'Усвояване'), ('RETENTION', 'Задържане')], max_length=16)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='quiz.item')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_items', to='quiz.quiz')),
            ],
            options={
                'ordering': ['quiz', 'position'],
                'unique_together': {('quiz', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('research_id', models.CharField(default=quiz.models.generate_research_id, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='quiz.cohort')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('cohort', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='quiz.student')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quiz.topic'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_option', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latency_ms', models.PositiveIntegerField()),
                ('quiz_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.quizitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.student')),
            ],
            options={
                'ordering': ['answered_at'],
                'unique_together': {('quiz_item', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AgentUsageMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.PositiveIntegerField()),
                ('self_reported_mode', models.CharField(choices=[('DELEGATED', 'Делегиране'), ('EXPLANATORY', 'Обяснително'), ('MIXED', 'Смесено'), ('NONE', 'Без агент')], max_length=16)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_modes', to='quiz.student')),
            ],
            options={
                'ordering': ['lecture'],
                'unique_together': {('student', 'lecture')},
            },
        ),
    ]
